baseURL = "https://selfscrum.xyz"
languageCode = "en-us"
canonifyURLs = false

title = "SELFSCRUM goes web3"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "moon"
reveal_cdn = "./reveal-js"
highlight_cdn = "./highlight-js"